# Generated by Django 6.0 on 2026-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botblock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
