# Generated by Django 6.0 on 2026-02-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("botblock", "0002_remove_customuser_phone_number_customuser_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
