# Generated by Django 6.0 on 2026-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите заголовок статьи",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите содержимое статьи", verbose_name="Содержимое"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью",
                        null=True,
                        upload_to="blog/previews/%Y/%m/%d/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте для публикации статьи",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Количество просмотров статьи",
                        verbose_name="Количество просмотров",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Автоматически заполняется из заголовка",
                        max_length=250,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="blog_blog_slug_d925e3_idx"),
                    models.Index(
                        fields=["created_at"], name="blog_blog_created_e997ae_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="blog_blog_is_publ_02e44a_idx"
                    ),
                ],
            },
        ),
    ]
