# Generated by Django 6.0 on 2026-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["slug"], name="blog_blog_slug_d925e3_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["created_at"], name="blog_blog_created_e997ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["is_published"], name="blog_blog_is_publ_02e44a_idx"
            ),
        ),
    ]
